class AppStrings {
  static String appname = "Mediapp",
      bestDocapp = "Best Doctor\n Appointment",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      login = "Login",
      signup = "Signup",
      forgetPassword = "Forget Password?",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Don't have an account?",
      search = "Search Doctor",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "SignOut",
      welcome = "Welcome",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney";
}
